version: '3'

services:
  rails:
    tty: true
    stdin_open: true
    image: rails-demo
    build: .
    volumes:
      - ./work:/work
    #`ports` option has no effect with `network_mode`
    #interchange them as your need
    network_mode: host
    # ports:
    #   - "3000:3000"
